/**
 * Gemini service for generating visual content.
 * Uses Gemini models for image generation (infographics, carousels, images).
 * Text content and briefs are generated by OpenAI GPT-4o.
 */

import { GoogleGenAI } from "@google/genai";
import { AI_CONFIG, getGoogleAIKey, getGeminiConfig } from './aiConfig';
import { MediaType, MediaContent, SocialContent } from '@/types/pipeline';
import {
    generateVideoBrief,
    generateSocialContent,
    generateImageGenPrompt,
    generateCarouselPrompts
} from './openaiService';

/**
 * Delay helper for retry logic
 */
function delay(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
}

/**
 * Delay with countdown logging
 */
async function delayWithCountdown(ms: number, label: string): Promise<void> {
    const totalSeconds = Math.ceil(ms / 1000);
    console.log(`[${label}] Rate limited. Waiting ${totalSeconds} seconds...`);

    for (let remaining = totalSeconds; remaining > 0; remaining--) {
        if (remaining % 10 === 0 || remaining <= 5) {
            console.log(`[${label}] Retry in ${remaining}s...`);
        }
        await delay(1000);
    }
}

/**
 * Call Gemini API for image generation with retry logic using SDK
 */
async function callGeminiImageAPI(prompt: string, apiKey: string, retries = 3): Promise<string | null> {
    const ai = new GoogleGenAI({ apiKey });
    const geminiConfig = getGeminiConfig();

    const config: any = {
        responseModalities: ["IMAGE", "TEXT"],
        imageConfig: {
            aspectRatio: "16:9",
            ...(geminiConfig.imageSize && { imageSize: geminiConfig.imageSize })
        }
    };

    if (geminiConfig.model === 'gemini-3-pro-image-preview') {
        config.tools = [{ googleSearch: {} }];
    }

    for (let attempt = 0; attempt <= retries; attempt++) {
        try {
            console.log(`[Gemini] Generating image with ${geminiConfig.model} (Attempt ${attempt + 1}/${retries + 1})...`);

            const responseStream = await ai.models.generateContentStream({
                model: geminiConfig.model,
                contents: { parts: [{ text: prompt }] },
                config: config
            });

            for await (const chunk of responseStream) {
                const parts = chunk.candidates?.[0]?.content?.parts || [];
                for (const part of parts) {
                    if (part.inlineData) {
                        return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
                    }
                }
            }

            console.warn('[Gemini] Stream completed but no image data found.');
            return null;

        } catch (error: any) {
            console.error('[Gemini] API error:', error);
            const isRateLimit = error?.status === 429 || error?.code === 429 || error?.message?.includes('429');

            if (isRateLimit && attempt < retries) {
                const waitTime = 5000 * Math.pow(2, attempt);
                await delayWithCountdown(waitTime, `Gemini Image (Attempt ${attempt + 1}/${retries})`);
                continue;
            }
            if (!isRateLimit) return null;
        }
    }
    return null;
}

/**
 * Generate media content using Gemini + OpenAI
 */
export async function generateMediaContent(
    selectedAngle: string,
    mediaType: MediaType
): Promise<MediaContent> {
    const apiKey = getGoogleAIKey();

    if (!apiKey) {
        throw new Error('Google AI / Gemini API key not configured.');
    }

    try {
        // Parallel fetch for prompts and content
        const [imagePrompt, socialContent, carouselPrompts] = await Promise.all([
            generateImageGenPrompt(selectedAngle, mediaType),
            generateSocialContent(selectedAngle, mediaType),
            mediaType === 'carousel' ? generateCarouselPrompts(selectedAngle) : Promise.resolve([])
        ]);

        console.log('[Gemini] Using image prompt:', imagePrompt);

        // Primary image generation
        const imageUrl = await callGeminiImageAPI(imagePrompt, apiKey);
        if (!imageUrl) {
            throw new Error('Gemini image generation failed.');
        }

        const content: MediaContent = {
            type: mediaType,
            imageUrl,
            caption: socialContent.caption,
            description: socialContent.description,
            hashtags: socialContent.hashtags,
        };

        // Handle Carousel Slides
        if (mediaType === 'carousel') {
            const additionalImages: string[] = [];

            if (carouselPrompts.length === 3) {
                // Generate Slide 2 & 3 using specific carousel prompts
                console.log('[Gemini] Generating carousel slide 2...');
                const img2 = await callGeminiImageAPI(carouselPrompts[1], apiKey);
                if (img2) additionalImages.push(img2);

                console.log('[Gemini] Generating carousel slide 3...');
                const img3 = await callGeminiImageAPI(carouselPrompts[2], apiKey);
                if (img3) additionalImages.push(img3);
            } else {
                // Fallback to variations
                console.log('[Gemini] Falling back to image variations for carousel...');
                const img2 = await callGeminiImageAPI(`${imagePrompt} -- Detail shot, close up, maintain style.`, apiKey);
                if (img2) additionalImages.push(img2);

                const img3 = await callGeminiImageAPI(`${imagePrompt} -- Wide shot, atmospheric, maintain style.`, apiKey);
                if (img3) additionalImages.push(img3);
            }

            content.previewUrls = [imageUrl, ...additionalImages];
        }

        // Handle Video Brief
        if (mediaType === 'video') {
            content.videoBrief = await generateVideoBrief(selectedAngle);
        }

        return content;
    } catch (error) {
        console.error('[Gemini Service] Error:', error);
        throw error;
    }
}

/**
 * Regenerate content with feedback
 */
export async function regenerateWithFeedback(
    selectedAngle: string,
    mediaType: MediaType,
    feedback: string
): Promise<MediaContent> {
    const enhancedAngle = `${selectedAngle}\n\nUSER FEEDBACK: ${feedback}`;
    return generateMediaContent(enhancedAngle, mediaType);
}

/**
 * Test Gemini API connection
 */
export async function testGeminiConnection(): Promise<{ success: boolean; message: string }> {
    const apiKey = getGoogleAIKey();
    if (!apiKey) return { success: false, message: 'No API key configured' };

    try {
        const ai = new GoogleGenAI({ apiKey });
        const geminiConfig = getGeminiConfig();

        await ai.models.generateContent({
            model: geminiConfig.model,
            contents: { parts: [{ text: "ping" }] },
            config: {
                responseModalities: ["IMAGE", "TEXT"],
                imageConfig: { aspectRatio: "16:9" }
            }
        });

        return { success: true, message: `Connected to ${geminiConfig.model}` };
    } catch (error: any) {
        return { success: false, message: error?.message || 'Connection failed' };
    }
}
